TOP=../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE

DB += ai.db
DB += ao.db
DB += bi.db
DB += bo.db
DB += li.db
DB += lo.db
DB += si.db
DB += mbbo3.db
DB += mbbo4.db
DB += scopeAnal.db
DB += scopeTrace.db
DB += scopeCmnd.db
DB += scopeCtrl.db
DB += scopeDiag.db
DB += scopeErr.db
DB += scopeMark.db
EB += timeDiv.db
DB += scope.db
DB += tds.db
DB += ds1.db
DB += ds6.db
DB += $(ASYN)/db/asynRecord.db

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE

